vigenere_table = """
KRYPTOSABCDEFGHIJLMNQUVWXZKRYP
RYPTOSABCDEFGHIJLMNQUVWXZKRYPT
YPTOSABCDEFGHIJLMNQUVWXZKRYPTO
PTOSABCDEFGHIJLMNQUVWXZKRYPTOS
TOSABCDEFGHIJLMNQUVWXZKRYPTOSA
OSABCDEFGHIJLMNQUVWXZKRYPTOSAB
SABCDEFGHIJLMNQUVWXZKRYPTOSABC
ABCDEFGHIJLMNQUVWXZKRYPTOSABCD
BCDEFGHIJLMNQUVWXZKRYPTOSABCDE
CDEFGHIJLMNQUVWXZKRYPTOSABCDEF
DEFGHIJLMNQUVWXZKRYPTOSABCDEFG
EFGHIJLMNQUVWXZKRYPTOSABCDEFGH
FGHIJLMNQUVWXZKRYPTOSABCDEFGHI
GHIJLMNQUVWXZKRYPTOSABCDEFGHIJL
HIJLMNQUVWXZKRYPTOSABCDEFGHIJL
IJLMNQUVWXZKRYPTOSABCDEFGHIJLM
JLMNQUVWXZKRYPTOSABCDEFGHIJLMN
LMNQUVWXZKRYPTOSABCDEFGHIJLMNQ
MNQUVWXZKRYPTOSABCDEFGHIJLMNQU
NQUVWXZKRYPTOSABCDEFGHIJLMNQUV
QUVWXZKRYPTOSABCDEFGHIJLMNQUVW
UVWXZKRYPTOSABCDEFGHIJLMNQUVWX
VWXZKRYPTOSABCDEFGHIJLMNQUVWXZ
WXZKRYPTOSABCDEFGHIJLMNQUVWXZK
XZKRYPTOSABCDEFGHIJLMNQUVWXZKR
ZKRYPTOSABCDEFGHIJLMNQUVWXZKRY
"""

alphabet = "KRYPTOSABCDEFGHIJLMNQUVWXZ"
alphabet_to_index_map = dict(map(lambda i: (alphabet[i], i), range(len(alphabet))))

vigenere_alphabets = vigenere_table.split()

while True:
    input_chars = input("Enter characters: ")

    coord1 = alphabet_to_index_map[input_chars[0]]
    coord2 = alphabet_to_index_map[input_chars[1]]

    vigenere_char = vigenere_alphabets[coord1][coord2]
    print(vigenere_char)
